BREVO_API_KEY = "YOUR_BREVO_API_KEY"

CLOUD_SQL_MYSQL_INSTANCE_CONNECTION_STRING = "YOUR_CLOUD_SQL_MYSQL_INSTANCE_CONNECTION_STRING"
CLOUD_SQL_MYSQL_DRIVER = "pymysql"
CLOUD_SQL_MYSQL_DB = "YOUR_CLOUD_SQL_MYSQL_DB"
CLOUD_SQL_MYSQL_USER = "YOUR_CLOUD_SQL_MYSQL_USER"
CLOUD_SQL_PASSWORD = "YOUR_CLOUD_SQL_PASSWORD"

FIREBASE_AUTH_WEB_API_KEY = "YOUR_FIREBASE_AUTH_WEB_API_KEY"
GEMINI_API_KEY = "YOUR_GEMINI_API_KEY"
GOOGLE_MAPS_DISTANCE_MATRIX_API_KEY = "YOUR_GOOGLE_MAPS_DISTANCE_MATRIX_API_KEY"

GCP_PROJECT_NAME = "YOUR_GCP_PROJECT_ID"
GCP_PROJECT_LOCATION = "YOUR_GCP_PROJECT_LOCATION"

OPENCAGE_GEOCODING_API_KEY = "YOUR_OPENCAGE_GEOCODING_API_KEY"
OPENROUTER_API_KEY = "YOUR_OPENROUTER_API_KEY"

TWILIO_PHONE_NUMBER = "YOUR_TWILIO_PHONE_NUMBER"
TWILIO_ACCOUNT_SID = "YOUR_TWILIO_ACCOUNT_SID"
TWILIO_AUTH_TOKEN = "YOUR_TWILIO_AUTH_TOKEN"
TWILIO_MESSAGING_SERVICE_SID = "YOUR_TWILIO_MESSAGING_SERVICE_SID"

URL_CLOUD_RUN_ONSITE_ENGINEER_ASSIGNMENT_SERVICE = "YOUR_CLOUD_RUN_ONSITE_ENGINEER_ASSIGNMENT_SERVICE_URL"

[auth]
redirect_uri = "YOUR_APP_URL/oauth2callback"
cookie_secret = "LONG_RANDOMLY_GENERATED_COOKIE_SECRET"

[auth.google]
client_id = "YOUR_GOOGLE_AUTH_APP_CLIENT_ID"
client_secret = "YOUR_GOOGLE_AUTH_APP_CLIENT_SECRET"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
